name: Bug Report
description: Mention details of what this bug is
title: [BUG]:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the KlinicCon-Frontend project.
  - type: markdown
    attributes:
      value: |
        Before filing a new issue, **please do a quick search** to check that it hasn't already been filed on the issue tracker. You can do this by going to [this link](https://github.com/rt4914/KlinicCon-Frontend/issues) and typing some words related to the issue in the search box next to the "New issue" button.
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the bug
      description: A concise description of what issue you're experiencing. **Example:** "When I click on the first lesson, I expect to be redirected to the lesson player, but instead the app crashes and shuts down."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior. **Example:** "1. Go to the topic page for Place Values. 2. Click on the first lesson. 3. See that the app shuts down."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen. **Example:** "I expect to be redirected to the lesson player screen."
    validations:
      required: true
  - type: textarea
    id: screenshots-or-videos
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or videos to help explain your problem.

        **Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: What device are you using?
      description: Please specify the device you're using.
      placeholder: Macbook Pro M1
    validations:
      required: false
  - type: input
    id: os-version
    attributes:
      label: What is your operating system version?
      description: Please specify the version of your operating system.
      placeholder: macOS 12.3.1
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: What browser are you using?
      description: Please specify the browser you're using.
      placeholder: Chrome
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: What is your browser version?
      description: Please specify the version of your browser.
      placeholder: Chrome xx.yy.zz version
    validations:
      required: false
  - type: input
    id: screen-resolution
    attributes:
      label: What is your screen resolution?
      description: Please specify your screen resolution.
      placeholder: 2560x1600
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
